blank_issues_enabled: false
contact_links:
  - name: Module Documentation
    url: 'https://vmware.github.io/powershell-module-for-vmware-cloud-foundation-jsongenerator'
    about: Having trouble with the module? Check out the documentation.
  - name: VMware Cloud Foundation Product Documentation
    url: 'https://techdocs.broadcom.com/en/VMware/Cloud-Foundation/index.html
    about: Find more information in the official VMware Cloud Foundation documentation.''
